# Generated by Django 5.0.1 on 2025-11-02 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa stada')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Stado',
                'verbose_name_plural': 'Stada',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=50, unique=True, verbose_name='NR ARIMR')),
                ('name', models.CharField(max_length=100, verbose_name='NAZWA')),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='NR PASZPORTU')),
                ('business_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numer działalności')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='DATA UR')),
                ('gender', models.CharField(choices=[('M', 'Samiec'), ('F', 'Samica')], default='F', max_length=1, verbose_name='PŁEĆ')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='RASA')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='MAŚĆ')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktywna'), ('SOLD', 'Sprzedana'), ('ARCHIVED', 'Zarchiwizowana')], db_index=True, default='ACTIVE', max_length=10, verbose_name='STATUS')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='DATA SPRZEDAŻY/PADNIĘCIA')),
                ('exit_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='NABYWCA/PRZYCZYNA')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KWOTA')),
                ('meat_delivery_date', models.DateField(blank=True, null=True, verbose_name='DOSTAWA MIĘSA')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='WAGA')),
                ('daily_weight_gain', models.FloatField(blank=True, null=True, verbose_name='PRZYROST/DZIEŃ')),
                ('pregnancy_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='DŁUGOŚĆ ISTNIEJĄCEJ CIĄŻY')),
                ('is_pregnancy_possible', models.CharField(blank=True, max_length=100, null=True, verbose_name='MOŻLIWOŚĆ BYCIA CIELNĄ')),
                ('relocation_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='RELOKACJA')),
                ('duplicates_to_make', models.CharField(blank=True, max_length=255, null=True, verbose_name='Duplikaty do założenia')),
                ('duplicates_to_order', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zamówić kolczyki duplikaty')),
                ('relocation_after_drive', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relokacja po przepędzie')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='UWAGI')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cows/', verbose_name='Zdjęcie (z aplikacji)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_dam', to='cows.cow', verbose_name='NR MATKI')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_sire', to='cows.cow', verbose_name='NR OJCA')),
                ('herd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cows', to='cows.herd', verbose_name='Stado')),
            ],
            options={
                'verbose_name': 'Krowa',
                'verbose_name_plural': 'Krowy',
                'ordering': ['tag_id'],
            },
        ),
        migrations.CreateModel(
            name='CowDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł / Opis')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Plik')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cows.cow', verbose_name='Krowa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Przesłane przez')),
            ],
            options={
                'verbose_name': 'Dokument krowy',
                'verbose_name_plural': 'Dokumenty krów',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LECZENIE', 'Leczenie'), ('SZCZEPIENIE', 'Szczepienie'), ('WYCIELENIE', 'Wycielenie'), ('KONTROLA', 'Kontrola'), ('INNE', 'Inne')], default='INNE', max_length=50, verbose_name='Typ zdarzenia')),
                ('date', models.DateField(verbose_name='Data zdarzenia')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cows.cow', verbose_name='Krowa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Zdarzenie (Historia)',
                'verbose_name_plural': 'Zdarzenia (Historia)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł zadania')),
                ('task_type', models.CharField(choices=[('WETERYNARZ', 'Wizyta weterynarza'), ('SZCZEPIENIE', 'Zaplanuj szczepienie'), ('BADANIE', 'Zaplanuj badanie'), ('PIELĘGNACJA', 'Pielęgnacja (np. korekcja racic)'), ('INNE', 'Inne zadanie')], default='INNE', max_length=50, verbose_name='Typ zadania')),
                ('due_date', models.DateField(db_index=True, verbose_name='Termin wykonania')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notatki')),
                ('is_completed', models.BooleanField(db_index=True, default=False, verbose_name='Wykonane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cows.cow', verbose_name='Krowa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
            ],
            options={
                'verbose_name': 'Zadanie (Kalendarz)',
                'verbose_name_plural': 'Zadania (Kalendarz)',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
