# Generated by Django 5.0.1 on 2025-11-02 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0003_alter_cow_options_cow_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_dam', to='cows.cow', verbose_name='Matka'),
        ),
        migrations.AddField(
            model_name='cow',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_sire', to='cows.cow', verbose_name='Ojciec'),
        ),
        migrations.CreateModel(
            name='CowDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł / Opis')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Plik')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cows.cow', verbose_name='Krowa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Przesłane przez')),
            ],
            options={
                'verbose_name': 'Dokument krowy',
                'verbose_name_plural': 'Dokumenty krów',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
